apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buildpolicies.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  names:
    kind: BuildPolicy
    plural: buildpolicies
  scope: Namespaced
